### ISSUE TITLE
Missing Subscription Get-AVDImageVersionStatus

### ISSUE THREAD

**Issue by iacavd** [srozemuller/AzAvd#28] opened 2022-04-05 15:30 UTC
PS Q:\Az.Avd> Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/versions?api-version=2022-01-03, {"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/versions?api-version=2022-01-03, {"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/versions?api-version=2022-01-03, {"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/versions?api-version=2022-01-03, {"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}

Note: Subscription has been explicitly selected before running this command

**Comment by srozemuller** [comment] 2022-04-06 06:31
I think something is wrong in filtering the correct image version id. To troubleshoot, are you able to run the following command and show the complete output.. looking for vmResources.properties.storageprofile.imagereference.id
`Get-AvdSessionHostResources -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName`

**Comment by iacavd** [comment] 2022-04-06 06:52
@srozemuller  This one works without errors (no information on the image though) 
How can I share results privately with you

**Comment by srozemuller** [comment] 2022-04-06 10:53
> 

@iacavd  you may send the results to my email sander@rozemuller.com or send me a DM on Twitter @sanderozemuller

**Comment by srozemuller** [comment] 2022-04-20 18:40
@iacavd I had someone else with the same issue. It looks like the issue is fixed in https://github.com/srozemuller/AzAvd/releases/tag/v3.0.1-beta.2
Could you please test the new release please.

**Comment by iacavd** [comment] 2022-04-21 08:31
@srozemuller 
PS Q:\Az.Avd> Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/subscriptions/##################/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001/versions?api-version=2022-01-03, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/subscriptions/##################/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001/versions?api-version=2022-01-03, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/subscriptions/##################/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001/versions?api-version=2022-01-03, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/subscriptions/##################/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001/versions?api-version=2022-01-03, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
PS Q:\Az.Avd>

**Comment by iacavd** [comment] 2022-04-21 08:34
Azure Compute Gallery is located in a separate resource group, can we add Shared Image Gallery resource group name as parameter?
$AVDArmResourcesResourceGroupName = "RG-SND-FJ-AVD-CEA-POC-AFC-001"
$HostPoolName = "AVD-HostPool-SND-FJ-POC-AFC-01"
**$SharedImageGalleryRG = "RG-SND-AVD-CEA-PRD-AFC-Shared-001"**

**Comment by iacavd** [comment] 2022-04-21 16:38
@srozemuller 
PS Q:\Az.Avd> Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName -Verbose
VERBOSE: Start searching
VERBOSE: Start searching for resources
VERBOSE: Start searching session hosts
VERBOSE: Using base url for getting all session hosts in $hostpoolName
VERBOSE: GET with 0-byte payload
VERBOSE: received 7697-byte response of content type application/json
VERBOSE: Content encoding: utf-8
VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-0.xyz.com
VERBOSE: GET with 0-byte payload
VERBOSE: received 8394-byte response of content type application/json
VERBOSE: Content encoding: utf-8
VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-1.xyz.com
VERBOSE: GET with 0-byte payload
VERBOSE: received 8470-byte response of content type application/json
VERBOSE: Content encoding: utf-8
VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-2.xyz.com
VERBOSE: GET with 0-byte payload
VERBOSE: received 8470-byte response of content type application/json
VERBOSE: Content encoding: utf-8
VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-3.xyz.com
VERBOSE: GET with 0-byte payload
VERBOSE: received 8394-byte response of content type application/json
VERBOSE: Content encoding: utf-8
VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-0.xyz.com
VERBOSE: Image ID is without a version. Image ID is correct allready
VERBOSE: Image ID found!, /subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001
VERBOSE: GET with 0-byte payload
VERBOSE: received 130-byte response of content type application/json
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001/versions?api-version=2022-01-03, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-1.xyz.com
VERBOSE: Image ID is without a version. Image ID is correct allready
VERBOSE: Image ID found!, /subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001
VERBOSE: GET with 0-byte payload
VERBOSE: received 130-byte response of content type application/json
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001/versions?api-version=2022-01-03, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-2.xyz.com
VERBOSE: Image ID is without a version. Image ID is correct allready
VERBOSE: Image ID found!, /subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001
VERBOSE: GET with 0-byte payload
VERBOSE: received 130-byte response of content type application/json
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001/versions?api-version=2022-01-03, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-3.xyz.com
VERBOSE: Image ID is without a version. Image ID is correct allready
VERBOSE: Image ID found!, /subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001
VERBOSE: GET with 0-byte payload
VERBOSE: received 130-byte response of content type application/json
WARNING: Someting went wrong when crawling for info at url https://management.azure.com/subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001/versions?api-version=2022-01-03, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}}
PS Q:\Az.Avd>

**Comment by srozemuller** [comment] 2022-04-21 16:43
@iacavd which PowerShell version are you using? 
Check with Get-Host

**Comment by srozemuller** [comment] 2022-04-21 16:45
> @srozemuller PS Q:\Az.Avd> Get-AvdImageVersionStatus -HostpoolName $HostPoolName -ResourceGroupName $AVDArmResourcesResourceGroupName -Verbose VERBOSE: Start searching VERBOSE: Start searching for resources VERBOSE: Start searching session hosts VERBOSE: Using base url for getting all session hosts in $hostpoolName VERBOSE: GET with 0-byte payload VERBOSE: received 7697-byte response of content type application/json VERBOSE: Content encoding: utf-8 VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-0.xyz.com VERBOSE: GET with 0-byte payload VERBOSE: received 8394-byte response of content type application/json VERBOSE: Content encoding: utf-8 VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-1.xyz.com VERBOSE: GET with 0-byte payload VERBOSE: received 8470-byte response of content type application/json VERBOSE: Content encoding: utf-8 VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-2.xyz.com VERBOSE: GET with 0-byte payload VERBOSE: received 8470-byte response of content type application/json VERBOSE: Content encoding: utf-8 VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-3.xyz.com VERBOSE: GET with 0-byte payload VERBOSE: received 8394-byte response of content type application/json VERBOSE: Content encoding: utf-8 VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-0.xyz.com VERBOSE: Image ID is without a version. Image ID is correct allready VERBOSE: Image ID found!, /subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001 VERBOSE: GET with 0-byte payload VERBOSE: received 130-byte response of content type application/json WARNING: Someting went wrong when crawling for info at url https://management.azure.com/subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001/versions?api-version=2022-01-03, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}} VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-1.xyz.com VERBOSE: Image ID is without a version. Image ID is correct allready VERBOSE: Image ID found!, /subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001 VERBOSE: GET with 0-byte payload VERBOSE: received 130-byte response of content type application/json WARNING: Someting went wrong when crawling for info at url https://management.azure.com/subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001/versions?api-version=2022-01-03, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}} VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-2.xyz.com VERBOSE: Image ID is without a version. Image ID is correct allready VERBOSE: Image ID found!, /subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001 VERBOSE: GET with 0-byte payload VERBOSE: received 130-byte response of content type application/json WARNING: Someting went wrong when crawling for info at url https://management.azure.com/subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001/versions?api-version=2022-01-03, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}} VERBOSE: Searching for AVD-HostPool-SND-FJ-POC-AFC-01/FJAVDAFC-3.xyz.com VERBOSE: Image ID is without a version. Image ID is correct allready VERBOSE: Image ID found!, /subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001 VERBOSE: GET with 0-byte payload VERBOSE: received 130-byte response of content type application/json WARNING: Someting went wrong when crawling for info at url https://management.azure.com/subscriptions/############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001/versions?api-version=2022-01-03, {"error":{"code":"ResourceGroupNotFound","message":"Resource group '$(AVD.SharedImageGalleryResourceGroup)' could not be found."}} PS Q:\Az.Avd>

Which PowerShell version are you using. You could check it with $PSVersionTable

**Comment by iacavd** [comment] 2022-04-21 17:53
@srozemuller 
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\>

**Comment by srozemuller** [comment] 2022-04-21 18:02
> Could you also check the VM storage profile with Get-AzVm -name vmname and provide the storageprofile object.

Could you also check the VM storage profile with Get-AzVm -name vmname and provide the storageprofile object.
Please without the use of variables

**Comment by srozemuller** [comment] 2022-04-21 18:02
> @srozemuller PS C:> $PSVersionTable
> 
> Name Value
> 
> PSVersion 7.2.2 PSEdition Core GitCommitId 7.2.2 OS Microsoft Windows 10.0.22000 Platform Win32NT PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…} PSRemotingProtocolVersion 2.3 SerializationVersion 1.1.0.1 WSManStackVersion 3.0
> 
> PS C:>

Could you also check the VM storage profile with Get-AzVm -name vmname and provide the storageprofile object.
Please without the use of variables

**Comment by srozemuller** [comment] 2022-04-21 18:10
> @srozemuller PS C:> $PSVersionTable
> 
> Name Value
> 
> PSVersion 7.2.2 PSEdition Core GitCommitId 7.2.2 OS Microsoft Windows 10.0.22000 Platform Win32NT PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…} PSRemotingProtocolVersion 2.3 SerializationVersion 1.1.0.1 WSManStackVersion 3.0
> 
> PS C:>

Could you also check the VM storage profile with Get-AzVm -name vmname and provide the storageprofile object.
Please without the use of variables

**Comment by iacavd** [comment] 2022-04-22 09:36
PS C:\> Get-AzVM -Name  FJAVDAFC-3 |fl

ResourceGroupName        : RG-SND-FJ-AVD-CEA-POC-AFC-001
Id                       : /subscriptions/###############/resourceGroups/RG-SND-FJ-AVD-CEA-POC-AFC-001/providers/Microsoft.Compute/virtual
                           Machines/FJAVDAFC-3
VmId                     : 4c64ac6b-2c5b-477e-80b7-1e5b85c0ec12
Name                     : FJAVDAFC-3
Type                     : Microsoft.Compute/virtualMachines
Location                 : francecentral
ExtendedLocation         :
LicenseType              : Windows_Client
Tags                     : {[ImageVersion, 202203.22.6], [Workload, Azure Virtual Desktop], [BusinessUnit, Fujitsu Consulting], [Environment, POC]…}
AvailabilitySetReference : Microsoft.Azure.Management.Compute.Models.SubResource
DiagnosticsProfile       : Microsoft.Azure.Management.Compute.Models.DiagnosticsProfile
Extensions               : {, , , …}
HardwareProfile          : Microsoft.Azure.Management.Compute.Models.HardwareProfile
InstanceView             :
NetworkProfile           : Microsoft.Azure.Management.Compute.Models.NetworkProfile
SecurityProfile          :
OSProfile                : Microsoft.Azure.Management.Compute.Models.OSProfile
BillingProfile           :
Plan                     :
ProvisioningState        : Succeeded
StorageProfile           : Microsoft.Azure.Management.Compute.Models.StorageProfile
DisplayHint              : Compact
Identity                 :
Zones                    : {}
FullyQualifiedDomainName :
AdditionalCapabilities   :
ProximityPlacementGroup  :
Host                     :
VirtualMachineScaleSet   :
EvictionPolicy           :
Priority                 :
HostGroup                :
RequestId                : 6bb3de31-3f04-475e-938a-1ed483c52dcf
StatusCode               : OK


PS C:\>

**Comment by iacavd** [comment] 2022-04-22 09:46
@srozemuller 
```

PS C:\> $VM.StorageProfile.ImageReference

Publisher    :
Offer        :
Sku          :
Version      :
ExactVersion : 202203.22.6
Id           : /subscriptions/#############/resourcegroups/$(AVD.SharedImageGalleryResourceGroup)/providers/Microsoft.Compute/galleries/
               SIGSNDAVDPRD001/images/IMG-AVD-Fujitsu-Win10-Desktop-Shared-001


PS C:\>
```

**Comment by iacavd** [comment] 2022-04-22 09:55
@srozemuller Platform Bug ?

**Comment by srozemuller** [comment] 2022-04-22 11:22
> @srozemuller Platform Bug ?

Thank you @iacavd  yea it seems there is a platform bug. The VM image id isn't correct. It looks like something is created in an automated may where the resourcegroup is mallformed. How did you create the vm's.

What is you create a new VM (in the portal) based on that image and then check the ID again from that machine.

**Closed** 2022-05-08 14:39 UTC
